# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [131]:
# your code here
import numpy as np
import random

#### 2. Print your NumPy version.

In [132]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [133]:
# Method 1
a = np.random.random((2,3,5))
a

array([[[0.04210229, 0.36705399, 0.69549745, 0.07035502, 0.14002006],
        [0.83740368, 0.03575041, 0.49118062, 0.104176  , 0.10495292],
        [0.26564885, 0.10235084, 0.96743155, 0.53397032, 0.10343803]],

       [[0.83447995, 0.23080216, 0.93691392, 0.98892154, 0.84906648],
        [0.6027879 , 0.46658575, 0.08133113, 0.37143029, 0.246415  ],
        [0.65825293, 0.95542718, 0.41039014, 0.77839127, 0.49324764]]])

In [136]:
# Method 2
np.random.sample((2,3,5))



array([[[0.32574504, 0.18218025, 0.31464629, 0.73373997, 0.89471016],
        [0.02955906, 0.24849648, 0.09705526, 0.16370875, 0.68626114],
        [0.84592147, 0.5064766 , 0.02430233, 0.17491935, 0.73299369]],

       [[0.30423206, 0.9079714 , 0.03495684, 0.3113057 , 0.67834451],
        [0.34971477, 0.38295244, 0.91202753, 0.40423472, 0.6726917 ],
        [0.9677141 , 0.34773755, 0.70657819, 0.08615539, 0.46201275]]])

In [135]:
# Method 3
np.random.rand(2,3,5)

array([[[0.18016772, 0.33705496, 0.70643587, 0.45023349, 0.61754948],
        [0.1859761 , 0.23955916, 0.51336315, 0.20849652, 0.4839876 ],
        [0.1064736 , 0.51243522, 0.51272532, 0.23522956, 0.6255685 ]],

       [[0.0668891 , 0.45960408, 0.28463139, 0.02264097, 0.54155883],
        [0.94936437, 0.61770658, 0.86638339, 0.56592366, 0.08416874],
        [0.57899763, 0.36722209, 0.82348125, 0.42104554, 0.66186465]]])

#### 4. Print *a*.


In [65]:
# your code here
a

array([[[0.01129104, 0.52029189, 0.90140312, 0.01667305, 0.68066602],
        [0.28036821, 0.3516199 , 0.42186923, 0.6561415 , 0.89938044],
        [0.50017118, 0.4443848 , 0.92744094, 0.57280813, 0.67800839]],

       [[0.28471794, 0.70248292, 0.44998465, 0.18400951, 0.22678586],
        [0.6688749 , 0.70211179, 0.73521602, 0.25174973, 0.14345067],
        [0.03084825, 0.17968132, 0.12003106, 0.16530746, 0.56759802]]])

In [69]:
a.shape

(2, 3, 5)

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [137]:
# your code here
b = np.ones((5,2,3))

#b = np.full((5,2,3),1)

#### 6. Print *b*.


In [138]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [68]:
b.shape

(5, 2, 3)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [140]:
print(a.size == b.size)

True


In [70]:
# your code here
print(a.shape == b.shape)

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [71]:
# your answer here
np.add(a, b)

#no because for addition the need to have the same shape 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [143]:
# your code here
c = b.transpose((1,2,0))
c.shape

#c = np.reshape(b, (2, 3,5))

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [77]:
# your code/answer here
d = a + c 
d

#Same shape

array([[[1.01129104, 1.52029189, 1.90140312, 1.01667305, 1.68066602],
        [1.28036821, 1.3516199 , 1.42186923, 1.6561415 , 1.89938044],
        [1.50017118, 1.4443848 , 1.92744094, 1.57280813, 1.67800839]],

       [[1.28471794, 1.70248292, 1.44998465, 1.18400951, 1.22678586],
        [1.6688749 , 1.70211179, 1.73521602, 1.25174973, 1.14345067],
        [1.03084825, 1.17968132, 1.12003106, 1.16530746, 1.56759802]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [80]:
# your code/answer here

print(a)
print('\n')
print(d)

# diff of 1 by adding the b array 

[[[0.01129104 0.52029189 0.90140312 0.01667305 0.68066602]
  [0.28036821 0.3516199  0.42186923 0.6561415  0.89938044]
  [0.50017118 0.4443848  0.92744094 0.57280813 0.67800839]]

 [[0.28471794 0.70248292 0.44998465 0.18400951 0.22678586]
  [0.6688749  0.70211179 0.73521602 0.25174973 0.14345067]
  [0.03084825 0.17968132 0.12003106 0.16530746 0.56759802]]]


[[[1.01129104 1.52029189 1.90140312 1.01667305 1.68066602]
  [1.28036821 1.3516199  1.42186923 1.6561415  1.89938044]
  [1.50017118 1.4443848  1.92744094 1.57280813 1.67800839]]

 [[1.28471794 1.70248292 1.44998465 1.18400951 1.22678586]
  [1.6688749  1.70211179 1.73521602 1.25174973 1.14345067]
  [1.03084825 1.17968132 1.12003106 1.16530746 1.56759802]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [81]:
# your code here
e = np.multiply(a, c)
e

array([[[0.01129104, 0.52029189, 0.90140312, 0.01667305, 0.68066602],
        [0.28036821, 0.3516199 , 0.42186923, 0.6561415 , 0.89938044],
        [0.50017118, 0.4443848 , 0.92744094, 0.57280813, 0.67800839]],

       [[0.28471794, 0.70248292, 0.44998465, 0.18400951, 0.22678586],
        [0.6688749 , 0.70211179, 0.73521602, 0.25174973, 0.14345067],
        [0.03084825, 0.17968132, 0.12003106, 0.16530746, 0.56759802]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [83]:
# your code/answer here
print(np.subtract(a, e))

#Yes because 

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [85]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [88]:
# your code here
f = np.empty((2,3,5))


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [144]:
{lambda x: 0 if x == d_min else 25 if x < d_mean else 50 if x == d_mean else 75 if x<d_max else 100}

{<function __main__.<lambda>(x)>}

In [150]:
f = np.array(list(map(lambda x: 0 if x == d_min else 25 if x < d_mean else 50 if x == d_mean else 75 if x<d_max else 100,d.ravel()))).reshape(2,3,5)




#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [151]:
# your code here
print(d)

[[[1.01129104 1.52029189 1.90140312 1.01667305 1.68066602]
  [1.28036821 1.3516199  1.42186923 1.6561415  1.89938044]
  [1.50017118 1.4443848  1.92744094 1.57280813 1.67800839]]

 [[1.28471794 1.70248292 1.44998465 1.18400951 1.22678586]
  [1.6688749  1.70211179 1.73521602 1.25174973 1.14345067]
  [1.03084825 1.17968132 1.12003106 1.16530746 1.56759802]]]


In [152]:
print(f)

[[[  0  75  75  25  75]
  [ 25  25  25  75  75]
  [ 75  75 100  75  75]]

 [[ 25  75  75  25  25]
  [ 75  75  75  25  25]
  [ 25  25  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [ ]:
# your code here